### ISSUE TITLE
Module discussion

### ISSUE THREAD

**Issue by fanatid** [bitcoinjs/bip32#1]
discussion in bitcoinjs-lib: https://github.com/bitcoinjs/bitcoinjs-lib/issues/508
I extracted some code from bitcoinjs-lib, repository -- https://github.com/fanatid/bip32
It's far from ideal, but at least we can start not from scratch.

**Comment by dcousens** [comment]
:+1: I'll see what I can do about bootstrapping this tomorrow

**Comment by jprichardson** [comment]
Ping pong @dcousens :stuck_out_tongue:

**Comment by dcousens** [comment]
Related to https://github.com/bitcoinjs/bip32/issues/2

**Comment by dcousens** [comment]
ping @axic,  I think that repo would be great to use under this.

I'm not sure of the best way to re-structure this all yet.
We have the following currently:

- bip32 (blank, but ideally `HDNode` equivalent from `bitcoinjs.HDNode`)
- bip32-path (path parsing/formatting utility)
- bip32-utils (discovery, account/chain/iterator modules)

All of them in the one place would be swell,  and it'd be great to maybe have some clear examples on `BIP44` and `BIP32` standards etc too.

Thoughts?

**Comment by jprichardson** [comment]
> ping @axic, I think bip32-path would be great to use here.

I think `bip32-path` would be great, but I think the API for bip32-path needs more clarity. For ref: https://github.com/axic/bip32-path/issues/1

**Comment by axic** [comment]
I'm happy to change the methods to have the new parameter convention if that matches the rest of the `bip32-*` modules.

**Comment by dcousens** [comment]
Parts of https://github.com/bitcoinjs/bitcoinjs-lib/issues/787 are related here in terms of how we handle `getAddress`.

If we can resolve that issue,  we can publish this module and use it within `bitcoinjs-lib`...

And if we do _that_,  we should be **that** much closer to using `secp256k1` rather than `ecurve` :dancer:

**Comment by dcousens** [comment]
Closing in favour of https://github.com/bitcoinjs/bip32/issues/4 and  ttps://github.com/bitcoinjs/bip32/issues/3
