### ISSUE TITLE
The hash algorithm in 'electron' does not support 'rmd160'

### ISSUE THREAD

**Issue by ontheroad1992** [bitcoinjs/bip32#13]
version: electron^4.0.6
const crypto = require('crypto')
console.log(crypto.getHashes())
// ["md4", "md5", "ripemd160", "sha1", "sha224", "sha256", "sha384", "sha512"]

**Comment by junderw** [comment]
can you provide a sample app we can build and reproduce?

I tried and could not reproduce.

**Comment by ontheroad1992** [comment]
> 你能提供我们可以构建和复制的示例应用吗？
> 
> 我试过，无法重现。

ok, I created a test project on 'github', please test it.
https://github.com/ontheroad1992/electron-test

**Comment by junderw** [comment]
![範囲を選択_001](https://user-images.githubusercontent.com/11246316/55069401-4e119580-50c7-11e9-91d0-4aed578d627e.png)

Thank you. I was able to reproduce.

**Comment by junderw** [comment]
Fixed and published as v2.0.1
