### ISSUE TITLE
Can't resolve 'vm' in warning from 'asn1.js' since 2.0.1

### ISSUE THREAD

**Issue by ignition42** [bitcoinjs/bip32#18]
I'm building a project with `angular`, using `angular-cli` for building. I'm also using `crypto-browserify`, this warning probably comes from it.

Since 2.0.1 this warning appears (ng serve or ng build):

```
WARNING in ./node_modules/asn1.js/lib/asn1/api.js
Module not found: Error: Can't resolve 'vm' in './node_modules/asn1.js/lib/asn1'
```
I don't know explicitly what ng runs internally, but I guess this warning comes from browserify or maybe webpack... not sure.

Downgrading to 2.0.0 the warning disappears.

@angular/cli: 7.3.7  
@angular/core: 7.2.0  
crypto-browserify: 3.12.0

**Comment by junderw** [comment]
Please check if fixed in #19
