### ISSUE TITLE
bip32-path

### ISSUE THREAD

**Issue by fanatid** [bitcoinjs/bip32#2]
@axic created useful package for checking derivation path, we can use it here
ref: https://www.npmjs.com/package/bip32-path

**Comment by dcousens** [comment]
I like it, indeed.
Would we want to be that liberal in the pathing we support though?  Or should we just standardize on what we have and let users use that utility for other syntaxes?

At the lease, we will link to it in this repository.

**Comment by dcousens** [comment]
ping @axic,  I think that repo would be great to use under this.

I'm not sure of the best way to re-structure this all yet.
We have the following currently:

- bip32 (blank, but ideally `HDNode` equivalent from `bitcoinjs.HDNode`)
- bip32-path (path parsing/formatting utility)
- bip32-utils (discovery, account/chain/iterator modules)

All of them in the one place would be swell,  and it'd be great to maybe have some clear examples on `BIP44` and `BIP32` standards etc too.

Thoughts?
