### ISSUE TITLE
Use bip32-path

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bip32#4]
Waiting on
- [ ] https://github.com/axic/bip32-path/issues/1 (we need `.isMaster()`)
- [ ] https://github.com/axic/bip32-path/pull/2 (for consistent error syntax)

**Comment by dcousens** [comment]
@axic are you able to look at the issues above?

**Comment by junderw** [comment]
Closing.

Currently I believe this isn't too much of a gain, and it seems axic is non-responsive.

Supporting 'h' notation and an array of numbers is not too much of a gain in my opinion.
