### ISSUE TITLE
I got this error  [RangeError: Range consisting of offset and length are out of bounds]

### ISSUE THREAD

**Issue by vtn-dev2016** [bitcoinjs/bip32#40]
When I call bip32.fromSeed() got this error  [RangeError: Range consisting of offset and length are out of bounds]. 
on React Native

**Comment by vtn-dev2016** [comment]
I found this problem with create-hmac

**Comment by eozturk1** [comment]
`fromSeed` takes `seed` and `network` parameters See [here](https://github.com/bitcoinjs/bip32/blob/master/src/bip32.js#L285). Can that be the problem?
