### ISSUE TITLE
Exporting public keys

### ISSUE THREAD

**Issue by eozturk1** [bitcoinjs/bip32#41]
I asked this on [StackOverflow](https://stackoverflow.com/questions/64940499/exporting-a-bip32-public-key-in-base64) but got no response.

How can one export the derived public keys in a non-binary format? For instance,

```
var node = bip32js.bip32.fromBase58('<some private key>');
var child = node.derivePath('m/0/0');
var publicKey = child.publicKey(); // This gets the public key for the child
console.log(btoa(publicKey)) // This gives an error since the returned public key is not a string

```

**Comment by junderw** [comment]
publicKey is a Buffer.

publicKey.toString('hex') will turn it into a hex string.
