### ISSUE TITLE
Non-hardened keys have... private keys?

### ISSUE THREAD

**Issue by eozturk1** [bitcoinjs/bip32#44]
A non-hardened child key should not have private key components -- as in:

```
var node = bip32js.bip32.fromBase58('<some_private_key');
var child = node.derive(0);
alert("Child: " + child.toBase58());
```
Interestingly, the child starts with `xprv` -- which should have been the case if `0'` were used for derivation. Am I missing something? Is this the expected behavior?

As a possible solution, `var child = node.derive(0).neutered();` prevents the child from being able to derive further private keys. Is this the suggested solution?

**Comment by junderw** [comment]
any key can be private, or public-only

the only difference is that if you want to derive hardened, you need the private key.

so neutering, then trying to deriveHardened will fail. Everything else will succeed and is normal.

if you want an xpub, neuter it.
