### ISSUE TITLE
Improve usage with hw-app-eth keys

### ISSUE THREAD

**Issue by SebastienGllmt** [bitcoinjs/bip32#56]
# Background

In `hw-app-eth`, to export a key, you're given the following interface:

`(path: string): Promise<{publicKey: string, address: string, chainCode?: string}>`

This is awkward to deal with because you're given the publicKey and not the **extended** public key (which is what is needed by libraries like this one). One way people tackle this is by [rewriting the logic](https://github.com/LedgerHQ/ledgerjs/issues/156) to calculate the extended key which is not ideal either.

# Why can't we solve this with this library currently?

There shouldn't be a need for users to have to copy-paste logic to recalculate the fingerprint needed for the extended public key because this library [already knows](https://github.com/bitcoinjs/bip32/blob/73b9ab40069e5b950d446b753b3dde7d7f3579c2/ts-src/crypto.ts) how to do this. However, this library doesn't make public the [right constructor](https://github.com/bitcoinjs/bip32/blob/master/ts-src/bip32.ts#L117) to able able to inject the proper values for depth, index and parent fingerprint and instead only providers [these constructors](https://github.com/bitcoinjs/bip32/blob/ff170dbea03fe4710c24aa550058e5775cf344d3/types/bip32.d.ts#L36).

# Solution

The solution, I believe, is to do the following:
1. Expose the crypto.ts file to users (currently it's not part of [bip32.ts](https://github.com/bitcoinjs/bip32/blob/ff170dbea03fe4710c24aa550058e5775cf344d3/types/bip32.d.ts))
2. Expose the BIP32Interface constructor (or an equivalent static function)

**Comment by SebastienGllmt** [comment]
>hdnode.parentFingerprint = parentHdnode.fingerprint.readUInt32BE(0);
    // "m/42" would be length === 2, but depth starts with m at depth 0, so 42 index is depth 1.
    hdnode.depth = pathArray.length - 1;
    hdnode.index = lastIndex(pathArray);

This code snippet is exactly what I want to do, but I cannot because `parentFingerprint`, `depth` and `index` are only exposed as getters (no setters) and there is no publicly exposed constructor I can use to manually set them either

https://github.com/bitcoinjs/bip32/blob/master/ts-src/bip32.ts#L138

**Comment by junderw** [comment]
Then just use ts-ignore (not needed if using JS)

```ts
    // @ts-ignore
    hdnode.__PARENT_FINGERPRINT = parentHdnode.fingerprint.readUInt32BE(0);
    // "m/42" would be length === 2, but depth starts with m at depth 0, so 42 index is depth 1.
    // @ts-ignore
    hdnode.__DEPTH = pathArray.length - 1;
    // @ts-ignore
    hdnode.__INDEX = lastIndex(pathArray);
```

**Comment by junderw** [comment]
Importing/exporting BIP32 from one library to another should be done with xpub/xprv strings.

I am not going to add foot guns to this library's public API just because some other library doesn't export properly.
