### ISSUE TITLE
Buffer is not defined

### ISSUE THREAD

**Issue by Sunnyjson** [bitcoinjs/bip32#60]
use bip32@^2.0.6, Compile error
```
Uncaught ReferenceError: Buffer is not defined
    at Object../node_modules/tiny-secp256k1/rfc6979.js (rfc6979.js:3:1)
    at Object.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at Object../node_modules/tiny-secp256k1/js.js (js.js:4:1)
    at Object.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at Object../node_modules/bip32/src/bip32.js (bip32.js:5:1)
    at Object.options.factory (react refresh:6:1)
```

**Comment by junderw** [comment]
More info plz.

**Comment by Sunnyjson** [comment]
@junderw  thanks for your reply， Currently I using bip32, the version is v2.0.5， When I try to use ‘
bip32.fromSeed(Buffer.from(seed, 'hex'))’， will get error message is Buffer is not defined

**Comment by junderw** [comment]
Buffer is always defined in NodeJS.

Please tell me where you are trying to use bip32.

More info.

**Comment by Sunnyjson** [comment]
this is my package.json
`"dependencies": {
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^12.1.4",
    "@testing-library/user-event": "^13.5.0",
    "bip32": "^3.0.1",
    "buffer": "^6.0.3",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-scripts": "^5.0.0",
    "stream": "npm:stream-browserify@^3.0.0",
    "stream-browserify": "^3.0.0",
    "tiny-secp256k1": "^2.2.1",
    "web-vitals": "^2.1.4"
  },`

yarn start will be got error

**Comment by emidev98** [comment]
Hey @junderw, 

I have the same problem when I use the library in browser-context. Seems like when using in node works fine because Buffer is provided as a native library.

**Comment by junderw** [comment]
Buffer is not a browser API and must be bundled and available for use.

Lately, certain bundlers have stopped automatically including Buffer when bundling, so you will need to manually add Buffer using whatever methods provided by your bundler.

**Comment by emidev98** [comment]
Exactly, leaving [this resource here](https://viglucci.io/how-to-polyfill-buffer-with-webpack-5) in case someone has the same problem and needs a solution
