### ISSUE TITLE
TypeError: bip32.fromSeed is not a function

### ISSUE THREAD

**Issue by spraveenitpro** [bitcoinjs/bip32#61]
Hi There,

I am trying to run the below code:

```
//Import dependencies
const bip32 = require('bip32')
const bip39 = require('bip39')
const bitcoin = require('bitcoinjs-lib')

//Define the network
const network = bitcoin.networks.bitcoin //use networks.testnet for testnet

// Derivation path
const path = `m/49'/0'/0'/0` // Use m/49'/1'/0'/0 for testnet

let mnemonic = bip39.generateMnemonic()
const seed = bip39.mnemonicToSeedSync(mnemonic)
let root = bip32.fromSeed(seed, network)

let account = root.derivePath(path)
let node = account.derive(0).derive(0)
let btcAddress = bitcoin.payments.p2pkh({
  pubkey: node.publicKey,
  network: network,
}).address

console.log(`
Wallet generated:
 - Address  : ${btcAddress},
 - Key : ${node.toWIF()}, 
 - Mnemonic : ${mnemonic}
     
`)
```

Node version 16.13.2
NPM version 8.6.0

I am running the above .js file like this:

![](https://d.pr/i/VwFf8B+)
[Direct Link](https://d.pr/i/VwFf8B+)

But getting the `TypeError: bip32.fromSeed is not a function` any idea what could be causing this? 

Thank you.

**Comment by junderw** [comment]
Please read the README after upgrading to a new major version.

v3 API has changed.

**Comment by spraveenitpro** [comment]
Hi @junderw 

Thanks for that tip, somehow i am unable to pin down this, what would you suggest replacing `let root = bip32.fromSeed(seed, network)` with? Just starting out, Thanks.

**Comment by junderw** [comment]
You did not read the README. Please read the README.

What are you unable to pin down? Which part of the README did you not understand?

**Comment by spraveenitpro** [comment]
So in this https://github.com/bitcoinjs/bip32/blob/master/src/bip32.js#L296 we can see that there is `function fromSeed` but in the [Readme](https://github.com/bitcoinjs/bip32/blob/master/README.md) there is no example of an equivalent function i.e.  something that takes the seed and the network  to return the root i.e. `let root = bip32.fromSeed(seed, network)` . Thanks.

**Comment by junderw** [comment]
Where is `bip32` defined in the README? Look for it.

Now look at where `bip32` is defined in your code.

Are you loading the API in the same way? Are you missing something?

**Comment by junderw** [comment]
Your code:
```js
const bip32 = require('bip32')
```

README:
```js
// ???
```

**Comment by junderw** [comment]
hint: look at `BIP32Factory` what does it do.
