### ISSUE TITLE
"Invalid network version" when calling the toWIF() method on derived private key

### ISSUE THREAD

**Issue by puskin94** [bitcoinjs/bip32#79]
Hi!  
I am 99% sure I am doing something wrong but I am getting the "Invalid network version" error when executing this code:

```js
export async function getSystemKeys(derivationKeyIndex): Promise<{publicKey: string; privateKey: string; address: string}> {
  const seed = await bip39.mnemonicToSeed('item lamp erase right project fan awake day crater where dance aspect')
  const root = bip32.fromSeed(seed)

  const path = `m/49'/1'/0'/0/${derivationKeyIndex}`;
  const derived = root.derivePath(path)

  const address = getAddress(derived.publicKey);

  const publicKey = derived.publicKey.toString('hex');
  const privateKey = derived.toWIF();

  return {publicKey, privateKey, address};
}

async function test() {
  const psbt = bitcoin.Psbt.fromHex(...);
  const {privateKey} = await getSystemKeys(10);

  console.log(privateKey);
  try {
    console.log(ECPair.fromWIF(privateKey, config.network));
  } catch (e) {
    console.log(e);
  }
}

test()
```

in this case, the private key I am getting is `L17wmnZK14fDZJHpo4W4VGQRHSCSkD8jUdSoUWMphBaupMFwkCgk`, the network is the `testnet` and, if I go putting logs into where the error is happening (https://github.com/bitcoinjs/ecpair/blob/d122cbf63a8ef820427086dd61353a64d6823c9a/src/ecpair.js#L35) I get this logs:

```
version 128
network {
  messagePrefix: '\x18Bitcoin Signed Message:\n',
  bech32: 'tb',
  bip32: { public: 70617039, private: 70615956 },
  pubKeyHash: 111,
  scriptHash: 196,
  wif: 239
}
network.wif 239
```

looking at the logs, the network I am passing to the method is the correct one, but the network of the generated wif is the mainnet.

What am I doing wrong?  
Thanks in advance!

**Comment by junderw** [comment]
`bip32.fromSeed(seed, config.network)`

If you figure out your mistake please post the answer so others can see. Thanks.

**Comment by puskin94** [comment]
> 

That is exactly what I was missing. In the provided examples I didn't see I could configure the network on the method, I found it while looking at the source code
