### ISSUE TITLE
How to derive usable address instead of extended key/public key

### ISSUE THREAD

**Issue by mannutech** [bitcoinjs/bip32#8]
So far I am able to derive the Bip32 object from the extended pub key but how to generate a specific receiving address or shareable format address using your module.

**Comment by junderw** [comment]
>  how to generate a specific receiving address or shareable format address using your module.

There is no concept of "address" in BIP32.

You must also require bitcoinjs-lib and use that.

The new payments API in v4 is great. Check the unit tests for usage examples.
