### ISSUE TITLE
Can not install bip32 library in nodejs project. Got MsBuildError 

### ISSUE THREAD

**Issue by officefish** [bitcoinjs/bip32#9]
Is there aby abbility ti nit use tiny-bs58check ?!

info cli using local version of lerna
lerna notice cli v3.4.3
lerna info versioning independent
lerna info bootstrap root only
yarn install v1.10.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error D:\nodejs\lerna-ark\node_modules\tiny-secp256k1: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: D:\nodejs\lerna-ark\node_modules\tiny-secp256k1
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.11.4 | win32 | x64
gyp info spawn C:\Users\RIK.windows-build-tools\python27\python.exe
gyp info spawn args [ 'D:\nodejs\lerna-ark\node_modules\node-gyp\gyp\gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'msvs',
gyp info spawn args '-G',
gyp info spawn args 'msvs_version=2015',
gyp info spawn args '-I',
gyp info spawn args 'D:\nodejs\lerna-ark\node_modules\tiny-secp256k1\build\config.gypi',
gyp info spawn args '-I',
gyp info spawn args 'D:\nodejs\lerna-ark\node_modules\node-gyp\addon.gypi',
gyp info spawn args '-I',
gyp info spawn args 'C:\Users\RIK\.node-gyp\8.11.4\include\node\common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=C:\Users\RIK\.node-gyp\8.11.4',
gyp info spawn args '-Dnode_gyp_dir=D:\nodejs\lerna-ark\node_modules\node-gyp',
gyp info spawn args '-Dnode_lib_file=C:\Users\RIK\.node-gyp\8.11.4\<(target_arch)\node.lib',
gyp info spawn args '-Dmodule_root_dir=D:\nodejs\lerna-ark\node_modules\tiny-secp256k1',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'D:\nodejs\lerna-ark\node_modules\tiny-secp256k1\build',
gyp info spawn args '-Goutput_dir=.' ]
gyp info spawn msbuild
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args '/clp:Verbosity=minimal',
gyp info spawn args '/nologo',
gyp info spawn args '/p:Configuration=Release;Platform=x64' ]
���ઠ �஥�⮢ � �⮬ �襭�� �� ������. �⮡� ������� ��ࠫ������ ᡮ��, ������� ��ࠬ��� "/m".
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v141 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install v141 build tools. Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [D:\nodejs\lerna-ark\node_modules\tiny-secp256k1\build\secp256k1.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: msbuild failed with exit code: 1
gyp ERR! stack at ChildProcess.onExit (D:\nodejs\lerna-ark\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack at emitTwo (events.js:126:13)
gyp ERR! stack at ChildProcess.emit (events.js:214:7)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\Program Files\nodejs\node.exe" "D:\nodejs\lerna-ark\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd D:\nodejs\lerna-ark\node_modules\tiny-secp256k1
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
lerna ERR! yarn install --mutex network:42424 --non-interactive exited 1 in 'root'
lerna ERR! yarn install --mutex network:42424 --non-interactive exited 1 in 'root'

**Comment by fanatid** [comment]
.... https://github.com/cryptocoinjs/secp256k1-node#windows
